# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursenumber', models.CharField(max_length=15)),
                ('career', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=10)),
                ('daytime', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=5)),
                ('sectionid', models.CharField(blank=True, max_length=10)),
                ('subsections', models.CharField(blank=True, max_length=5000)),
                ('coursetype', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
