# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_testinstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstructor',
            name='instructor_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
