# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_delete_testinstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('icid', models.IntegerField(primary_key=True, serialize=False)),
                ('dept', models.CharField(blank=True, max_length=30)),
                ('fname', models.CharField(blank=True, default='', max_length=50)),
                ('lname', models.CharField(blank=True, default='', max_length=50)),
                ('pos1', models.CharField(blank=True, default='', max_length=30)),
                ('pos2', models.CharField(blank=True, default='', max_length=30)),
                ('pos3', models.CharField(blank=True, default='', max_length=30)),
                ('pos4', models.CharField(blank=True, default='', max_length=30)),
                ('pos5', models.CharField(blank=True, default='', max_length=30)),
                ('pos6', models.CharField(blank=True, default='', max_length=30)),
                ('neg1', models.CharField(blank=True, default='', max_length=30)),
                ('neg2', models.CharField(blank=True, default='', max_length=30)),
                ('neg3', models.CharField(blank=True, default='', max_length=30)),
                ('neg4', models.CharField(blank=True, default='', max_length=30)),
                ('neg5', models.CharField(blank=True, default='', max_length=30)),
                ('neg6', models.CharField(blank=True, default='', max_length=30)),
                ('coursenum_response', models.IntegerField()),
                ('courseavg_score', models.FloatField()),
                ('instructor_id', models.IntegerField()),
                ('coursename', models.CharField(blank=True, default='', max_length=30)),
                ('coursetitle', models.CharField(blank=True, default='', max_length=30)),
                ('courseid', models.IntegerField()),
            ],
        ),
    ]
