# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chooseins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins1', models.CharField(max_length=30)),
                ('ins2', models.CharField(blank=True, max_length=30)),
                ('ins3', models.CharField(blank=True, max_length=30)),
                ('ins4', models.CharField(blank=True, max_length=30)),
                ('ins5', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('career', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=10)),
                ('coursenumber', models.CharField(max_length=15)),
                ('daytime', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=5)),
                ('sectionid', models.CharField(blank=True, max_length=10)),
                ('subsections', models.CharField(blank=True, max_length=5000)),
                ('coursetype', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='chooseins',
            name='courseins',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Question'),
        ),
    ]
