# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170310_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinstructor',
            fields=[
                ('instructor_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('dept', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('pos1', models.CharField(blank=True, default='', max_length=30)),
                ('pos2', models.CharField(blank=True, default='', max_length=30)),
                ('pos3', models.CharField(blank=True, default='', max_length=30)),
                ('pos4', models.CharField(blank=True, default='', max_length=30)),
                ('pos5', models.CharField(blank=True, default='', max_length=30)),
                ('pos6', models.CharField(blank=True, default='', max_length=30)),
                ('neg1', models.CharField(blank=True, default='', max_length=30)),
                ('neg2', models.CharField(blank=True, default='', max_length=30)),
                ('neg3', models.CharField(blank=True, default='', max_length=30)),
                ('neg4', models.CharField(blank=True, default='', max_length=30)),
                ('neg5', models.CharField(blank=True, default='', max_length=30)),
                ('neg6', models.CharField(blank=True, default='', max_length=30)),
                ('num_response', models.IntegerField()),
                ('avg_score', models.FloatField()),
            ],
        ),
    ]
