# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170310_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinstructor',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='testinstructor',
            old_name='last_name',
            new_name='lname',
        ),
    ]
